### ISSUE TITLE
GitHub to LinkedIn

### ISSUE THREAD

**Issue by flexbox** [flexbox/weshipit.today#88]
**Phase 1**
- [x] Create a new project
- [x] Add Nextauth https://next-auth.js.org/getting-started/example
- [ ] create a landing page https://www.mixo.io/site/git-link-ai-9ghoo/index.html
- [ ] Github connect
- [ ] Linkedin connect

**Phase 2**
- [ ] Webhook listen to github event on /api folder
- [ ] Call OpenAI api
- [ ] Share results on LinkedIn 

**Phase 3**
- [ ] Stripe payment link
